# docker-compose.yaml
version: '3.8'
services:
  jenkins_master:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    environment:
      - TZ=America/Denver
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /var/jenkins_home
    ports:
      - 127.0.0.1:2345:2345
      - 8080:8080
      - 50000:50000
  jenkins_slave:
    image: jenkins/jnlp-slave
    container_name: jnlp_slave
    user: root
    command: -url http://192.168.8.113:8080 <secret> <jenkins_slave>
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /var/jenkins_home